const amenityImages = {
  Wifi: '/images/amenities/wifi.svg',
  'Free Parking': '/images/amenities/freeParking.svg',
  'Paid Parking': '/images/amenities/paidParking.png',
  'Public Transportation': '/images/amenities/publicTransportation.png',
  'EV Charging Station': '/images/amenities/ev.png',
  'Handicap Accessibility': '/images/amenities/disabled.png',
  Restrooms: '/images/amenities/restroom.svg',
  'Cot / Baby crib': '/images/amenities/babyCrib.png',
  Highchair: '/images/amenities/highchair.png',
  'Air Conditioning': '/images/amenities/airConditioning.png',
  TV: '/images/amenities/TV.svg',
  Kitchen: '/images/amenities/kitchen.png',
  'BBQ Grill': '/images/amenities/grill.png',
  'Fire Pit': '/images/amenities/firePit.png',
  'Indoor Fireplace': '/images/amenities/fireplace.png',
  'Outdoor Shower': '/images/amenities/shower.png',
  'Washing Machine': '/images/amenities/washingMachine.png',
  Dishwasher: '/images/amenities/dishwasher.png',
  Pool: '/images/amenities/pool.png',
  'Hot tub': '/images/amenities/hotTub.png',
  Sauna: '/images/amenities/sauna.png',
  Tennis: '/images/amenities/tennis.png',
  'Beach Access': '/images/amenities/beachAccess.png',
  'Lake Access': '/images/amenities/lakeAccess.png',
  'Diving Access': '/images/amenities/divingAccess.png',
  Fishing: '/images/amenities/fishing.png',
  Riding: '/images/amenities/riding.png',
  'Exercise Nearby': '/images/amenities/exercise.png',
  Hunting: '/images/amenities/hunting.png',
  Golf: '/images/amenities/golf.png',
  Ski: '/images/amenities/ski.png',
  'First Aid Kit': '/images/amenities/firstAidKit.png',
  'Fire Extinguisher': '/images/amenities/fireExtinguisher.png',
  'Smoke Alarm': '/images/amenities/smokeAlarm.png',
};

export default amenityImages;
